[package]
name = "payouts"
version = "0.0.5"
edition = "2021"

[dependencies]
dlc-trie = { version = "0.4.0", path = "../../../libs/rust-dlc/master/dlc-trie", features = [ "use-serde"] }
dlc = { version = "0.4.0", path = "../../../libs/rust-dlc/master/dlc", features = [ "use-serde"] }
dlc-manager = { version = "0.4.0", path = "../../../libs/rust-dlc/master/dlc-manager", features = [ "use-serde"] }
dlc-messages = { version = "0.4.0", path = "../../../libs/rust-dlc/master/dlc-messages", features = [ "use-serde"] }
bitcoin = "0.30.2"
