[package]
name = "ddk-payouts"
version = "0.0.10"
authors = ["benny b <ben@bitcoinbay.foundation>"]
description = "Library to build payout functions for DLC contracts."
license = "MIT"
repository = "https://github.com/bennyhodl/dlcdevkit"
edition = "2021"

[dependencies]
dlc-trie = { version = "0.5.0", features = [ "use-serde"] }
dlc = { version = "0.5.0", features = [ "use-serde"] }
dlc-manager = { version = "0.5.0", features = [ "use-serde"] }
dlc-messages = { version = "0.5.0", features = [ "use-serde"] }
bitcoin = "0.30.2"
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
anyhow = "1.0.86"
