[package]
name = "ddk-node"
version = "0.0.11"
authors = ["benny b <ben@bitcoinbay.foundation>"]
description = "DDK node to facilitate DLC contracts."
license = "MIT"
repository = "https://github.com/bennyhodl/dlcdevkit"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.9", features = ["derive"] }
ddk = { version = "0.0.10", path = "../ddk/" }
hex = "0.4.3"
homedir = "0.3.3"
inquire = "0.7.5"
prost = "0.12.1"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.125"
tokio = { version = "1.38.0", features = ["full"] }
toml = "0.8.19"
tonic = "0.10.2"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
ddk-payouts = { version = "0.0.10", path = "../payouts" }
reqwest = "0.12.7"

[build-dependencies]
tonic-build = "0.10.2"

[[bin]]
name = "ddk-node"
path = "./src/bin/node.rs"

[[bin]]
name = "ddk-cli"
path = "./src/bin/cli.rs"

